version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}
    mongo_data: {}

networks:
  front-tier:
        driver: bridge
  back-tier:
        driver: bridge

services:
  prediction_service:
    build:
      context: monitoring/prediction_service
      dockerfile: Dockerfile
    depends_on:
      - evidently_service
      - mongo
    environment:
      EVIDENTLY_SERVICE: "http://evidently_service.:8877"
      MONGODB_ADDRESS: "mongodb://mongo.:27017/"
    ports:
      - "9696:9696"
    networks:
      - back-tier
      - front-tier

  evidently_service:
    build:
      context: monitoring/evidently_service
      dockerfile: Dockerfile
    depends_on:
      - grafana
    volumes:
      - ./monitoring/evidently_service/datasets:/app/datasets
      - ./monitoring/evidently_service/config.yaml:/app/config.yaml
    ports:
      - "8877:8877"
    networks:
      - back-tier
      - front-tier

  prometheus:
    image: prom/prometheus
    depends_on:
      - mongo
    volumes:
      - ./monitoring/evidently_service/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9091:9090"
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/evidently_service/config/grafana_datasources.yml:/etc/grafana/provisioning/datasources/grafana_datasources.yml:ro
      - ./monitoring/evidently_service/config/grafana_dashboards.yml:/etc/grafana/provisioning/dashboards/grafana_dashboards.yml:ro
      - ./monitoring/evidently_service/dashboards:/opt/grafana/dashboards
      - ./monitoring/grafana_data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./monitoring/mongo_data:/data/db
    networks:
      - back-tier

