version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}
    mongo_data: {}

networks:
  front-tier:
        driver: bridge
  back-tier:
        driver: bridge

services:
  prediction_service:
    container_name: prediction_service
    image: prediction_service
    build:
      context: monitoring/prediction_service
      dockerfile: Dockerfile
    depends_on:
      - evidently_service
      - mongo
    environment:
      EVIDENTLY_SERVICE: "http://evidently_service.:8877"
      MLFLOW_TRACKING_URI: "http://mlflow_server:5050"
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/mlops-credit-risk-secret.json
    volumes:
      - /Users/jakob/.secrets/mlops-credit-risk-secret.json:/secrets/mlops-credit-risk-secret.json
    ports:
      - "9696:9696"
    networks:
      - back-tier
      - front-tier

  evidently_service:
    container_name: evidently_service
    image: evidently_service
    build:
      context: monitoring/evidently_service
      dockerfile: Dockerfile
    depends_on:
      - grafana
    volumes:
      - ./monitoring/evidently_service/datasets:/app/datasets
      - ./monitoring/evidently_service/config.yaml:/app/config.yaml
    ports:
      - "8877:8877"
    networks:
      - back-tier
      - front-tier

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    depends_on:
      - mongo
    volumes:
      - ./monitoring/evidently_service/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9091:9090"
    networks:
      - back-tier
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/evidently_service/config/grafana_datasources.yml:/etc/grafana/provisioning/datasources/grafana_datasources.yml:ro
      - ./monitoring/evidently_service/config/grafana_dashboards.yml:/etc/grafana/provisioning/dashboards/grafana_dashboards.yml:ro
      - ./monitoring/evidently_service/dashboards:/opt/grafana/dashboards
      - ./monitoring/grafana_data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./monitoring/mongo_data:/data/db
    networks:
      - back-tier

  mlflow_server:
    restart: always
    build:
      context: ./model_orchestration_and_tracking
      dockerfile: Dockerfile-mlflow
    container_name: mlflow_server
    image: mlflow_server
    ports:
      - 5051:5050
    networks:
      - back-tier
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/mlops-credit-risk-secret.json
    volumes:
      - /tmp/mlopsdb:/tmp/mlopsdb
      - /tmp/mlopsartifacts:/tmp/mlopsartifacts
      - /tmp/store:/tmp/store
      - /Users/jakob/.secrets/mlops-credit-risk-secret.json:/secrets/mlops-credit-risk-secret.json
  
  prefect_server:
    restart: always
    build:
      context: ./model_orchestration_and_tracking
      dockerfile: Dockerfile-prefect
    logging:
      driver: none
    image: prefect_server
    container_name: prefect_server
    ports:
      - 4200:4200
      - 8081:8081
    env_file:
      - ./model_orchestration_and_tracking/.env
    networks:
      - back-tier
    volumes:
      - /tmp/mlopsdb:/tmp/mlopsdb
      - /tmp/mlopsartifacts:/tmp/mlopsartifacts
      - /tmp/store:/tmp/store
    
  prefect_agent:
    restart: always
    depends_on:
      - prefect_server
      - mlflow_server
    build:
      context: ./model_orchestration_and_tracking
      dockerfile: Dockerfile-prefect-agent
    image: prefect_agent1
    container_name: prefect_agent1
    environment:
      MONGODB_ADDRESS: "mongodb://127.0.0.1:27017"
      REPORTS_FOLDER: /tmp/mlreports
      REPORT_TIME_WINDOW_MINUTES: 180
      EVIDENTLY_TIME_WIDTH_MINS: 720
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/mlops-credit-risk-secret.json
      MLFLOW_TRACKING_URI: "http://mlflow_server:5050"
    volumes:
      - /tmp/mlopsdb:/tmp/mlopsdb
      - /tmp/mlopsartifacts:/tmp/mlopsartifacts
      - /tmp/store:/tmp/store
      - /tmp/mlreports:/tmp/mlreports
      - /Users/jakob/.secrets/mlops-credit-risk-secret.json:/secrets/mlops-credit-risk-secret.json
    networks:
      - back-tier
  
  reporting:
    restart: always
    container_name: reporting_agent
    image: reporting_agent
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    depends_on:
      - prefect_server
      - mlflow_server
      - mongo
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/mlops-credit-risk-secret.json
    volumes:
      - /Users/jakob/.secrets/mlops-credit-risk-secret.json:/secrets/mlops-credit-risk-secret.json
    networks:
      - back-tier



