{
 "title": "Evidently Data Drift Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dataset_name", "query": { "query": "label_values(dataset_name)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Evidently Data Drift Monitoring for client Credit Risk\n\n  You can add additional information about the dashboard and its usage here.\n"
   }
  },
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Dataset Drift",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "evidently:data_drift:dataset_drift{dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "dataset drift"
    }
   ]
  },
  {
   "title": "Share of drifted features",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "evidently:data_drift:share_drifted_features{dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "share"
    }
   ]
  },
  {
   "title": "# of drifted features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features{dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "Drifted"
    }
   ]
  },
  {
   "title": "# of features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features{dataset_name=\"${dataset_name:raw}\"} / evidently:data_drift:share_drifted_features{dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Detailed information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Feature Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "evidently:data_drift:p_value{dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "{{feature}}"
    },
    {
     "expr": "evidently:reference_dataset_hash",
     "legendFormat": "reference_hash"
    }
   ]
  }
 ]
}