FROM python:3.9.16-slim

COPY requirements-mlflow.txt .

RUN pip install -r requirements-mlflow.txt

WORKDIR /mlops

EXPOSE 5050

CMD mlflow server --backend-store-uri file:///mlops/mlruns --port 5050 --default-artifact-root gs://mlops-credit-risk/mlruns --serve-artifacts --host 0.0.0.0